# Generated by Django 4.1.7 on 2023-04-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=150, verbose_name='first name')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='отчество')),
                ('last_name', models.CharField(default=None, max_length=150, verbose_name='last name')),
            ],
        ),
    ]
