# Generated by Django 4.1.7 on 2023-04-14 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='client',
            name='act_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата акта(дата чека)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='client',
            name='contract_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата договора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default="70000000000", max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.CharField(choices=[('Moscow', 'Москва'), ('Moscow region', 'Московская область')], default=('Moscow region', 'Московская область'), max_length=128, verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('in work', 'Принят в работу'), ('issued', 'Выдан'), ('docs submitted', 'Документы сданы'), ('payment to client', 'Оплата клиенту'), ('payment', 'Оплата')], max_length=150, verbose_name='Статус')),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий(примечание)')),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
