# Generated by Django 4.1.7 on 2023-04-14 13:40

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_client_act_date_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='act_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата акта(дата чека)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(choices=[('Moscow', 'Москва'), ('Moscow region', 'Московская область')], default=None, max_length=128, verbose_name='Регион'),
        ),
    ]
