# Generated by Django 4.1.7 on 2023-04-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_act_date_alter_client_contract_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='IPR',
            field=models.BooleanField(default=False, verbose_name='ИПР'),
        ),
        migrations.AddField(
            model_name='client',
            name='SNILS',
            field=models.BooleanField(default=False, verbose_name='СНИЛС'),
        ),
        migrations.AddField(
            model_name='client',
            name='SprMSE',
            field=models.BooleanField(default=False, verbose_name='СпрМСЭ'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_detail',
            field=models.BooleanField(default=False, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='client',
            name='contour',
            field=models.BooleanField(default=False, verbose_name='Контур'),
        ),
        migrations.AddField(
            model_name='client',
            name='parts',
            field=models.BooleanField(default=False, verbose_name='Комплектующие'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport',
            field=models.BooleanField(default=False, verbose_name='Паспорт'),
        ),
    ]
