# Generated by Django 4.1.7 on 2023-04-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_rename_bank_detail_client_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Адрес'),
        ),
    ]
