# Generated by Django 4.1.7 on 2023-04-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Стоимость, руб.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='status',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='clients.client', verbose_name='Клиент'),
        ),
    ]
