# Generated by Django 4.1.7 on 2023-04-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_cost_alter_comment_client_alter_status_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('in work', 'Принят в работу'), ('issued', 'Выдан'), ('docs submitted', 'Документы сданы'), ('payment to client', 'Оплата клиенту'), ('payment', 'Оплата')], max_length=150, verbose_name='Статус'),
        ),
    ]
