# Generated by Django 4.1.7 on 2023-04-14 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0008_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='how_contacted',
            field=models.CharField(choices=[('they_called', 'Звонок'), ('we_called', 'Обзвон'), ('via_pro', 'Через протезиста')], default='they_called', max_length=150, verbose_name='Откуда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='prosthetist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Протезист'),
        ),
        migrations.AlterField(
            model_name='client',
            name='act_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата акта(чека)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank_details',
            field=models.BooleanField(default=False, help_text='Реквизиты', verbose_name='Рекв.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contour',
            field=models.BooleanField(default=False, help_text='Выпуск в контуре', verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='client',
            name='parts',
            field=models.BooleanField(default=False, help_text='Протезист дал комплектующие', verbose_name='Компл.'),
        ),
    ]
