# Generated by Django 4.1.7 on 2023-04-14 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0009_client_how_contacted_client_prosthetist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default=None, max_length=150, verbose_name='last name')),
                ('first_name', models.CharField(default=None, max_length=150, verbose_name='first name')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='отчество')),
                ('how_contacted', models.CharField(choices=[('they_called', 'Звонок'), ('we_called', 'Обзвон'), ('via_pro', 'Через протезиста')], max_length=150, verbose_name='Откуда')),
                ('call_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата звонка')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, max_length=1000, verbose_name='Адрес')),
                ('last_prosthesis_date', models.CharField(blank=True, default='первичн', help_text='Примерная дата получения последнего протеза', max_length=150, verbose_name='Пред. протез')),
                ('call_result', models.CharField(blank=True, max_length=1024, verbose_name='Результат звонка')),
                ('comment', models.CharField(blank=True, help_text='Комментарий протезиста', max_length=1024, verbose_name='Комментарий')),
                ('MTZ_date', models.DateField(blank=True, null=True, verbose_name='МТЗ')),
                ('result', models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], help_text='Согласились или нет', max_length=16, null=True, verbose_name='Результат(да/нет)')),
                ('prosthetist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Протезист')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
    ]
