# Generated by Django 4.1.7 on 2023-04-21 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_status_options_alter_status_name_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('status', models.CharField(blank=True, choices=[('in work', 'Принят в работу'), ('issued', 'Выдан'), ('docs submitted', 'Документы сданы'), ('payment to client', 'Оплата клиенту'), ('payment', 'Оплата')], max_length=150, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prosthetist',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='how_contacted',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='prosthetist',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='surname',
        ),
        migrations.AddField(
            model_name='contact',
            name='prosthesis_type',
            field=models.CharField(blank=True, max_length=150, verbose_name='Протез'),
        ),
        migrations.AlterField(
            model_name='client',
            name='how_contacted',
            field=models.CharField(max_length=150, verbose_name='Откуда обратились'),
        ),
    ]
