# Generated by Django 4.1.7 on 2023-04-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('in work', 'Принят в работу'), ('issued', 'Выдан'), ('docs submitted', 'Документы сданы'), ('payment to client', 'Оплата клиенту'), ('payment', 'Оплата')], max_length=150, verbose_name='Статус'),
        ),
    ]
