# Generated by Django 4.1.7 on 2023-05-01 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0019_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='prosthetist',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_prosthetist': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Протезист'),
        ),
        migrations.AlterField(
            model_name='job',
            name='prosthetist',
            field=models.ForeignKey(limit_choices_to={'is_prosthetist': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Протезист'),
        ),
    ]
