# Generated by Django 4.2 on 2023-05-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_delete_prosthesismodel_alter_item_options_and_more'),
        ('clients', '0021_alter_job_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='prosthesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.prosthesis', verbose_name='Протез'),
        ),
    ]
