# Generated by Django 4.2 on 2023-07-09 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0061_remove_item_warehouse'),
        ('clients', '0022_alter_job_prosthesis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'работа', 'verbose_name_plural': 'работы'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'статус', 'verbose_name_plural': 'статусы'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='act_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contract_date',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, max_length=1000, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank_details',
            field=models.BooleanField(default=False, help_text='реквизиты', verbose_name='рекв.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contour',
            field=models.BooleanField(default=False, help_text='выпуск в контуре', verbose_name='контур'),
        ),
        migrations.AlterField(
            model_name='client',
            name='how_contacted',
            field=models.CharField(max_length=150, verbose_name='откуда обратились'),
        ),
        migrations.AlterField(
            model_name='client',
            name='parts',
            field=models.BooleanField(default=False, help_text='протезист дал комплектующие', verbose_name='компл.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='prosthetist',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_prosthetist': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='протезист'),
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(blank=True, choices=[('Moscow', 'Москва'), ('Moscow region', 'Московская область')], default=None, max_length=128, verbose_name='регион'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clients.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='комментарий(примечание)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='call_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата звонка'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='call_result',
            field=models.CharField(blank=True, max_length=1024, verbose_name='результат звонка'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.CharField(blank=True, help_text='комментарий протезиста', max_length=1024, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_prosthesis_date',
            field=models.CharField(blank=True, default='первичн.', help_text='примерная дата получения последнего протеза', max_length=150, verbose_name='предыдущий протез'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prosthesis_type',
            field=models.CharField(blank=True, max_length=150, verbose_name='протез'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='result',
            field=models.CharField(blank=True, choices=[('yes', 'да'), ('no', 'нет')], help_text='согласились или нет', max_length=16, verbose_name='результат'),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clients.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='prosthesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.prosthesis', verbose_name='протез'),
        ),
        migrations.AlterField(
            model_name='job',
            name='prosthetist',
            field=models.ForeignKey(limit_choices_to={'is_prosthetist': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='протезист'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('in work', 'принят в работу'), ('issued', 'выдан'), ('docs submitted', 'документы сданы'), ('payment to client', 'оплата клиенту'), ('payment', 'оплата')], max_length=150, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='status',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='clients.job', verbose_name='работа'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('in work', 'принят в работу'), ('issued', 'выдан'), ('docs submitted', 'документы сданы'), ('payment to client', 'оплата клиенту'), ('payment', 'оплата')], max_length=150, verbose_name='статус'),
        ),
    ]
