# Generated by Django 4.2 on 2023-07-09 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_client_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='client',
        ),
        migrations.AddField(
            model_name='comment',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clients.contact', verbose_name='контакт'),
            preserve_default=False,
        ),
    ]
