# Generated by Django 4.2 on 2023-07-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_remove_comment_client_comment_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
