# Generated by Django 4.2 on 2023-07-10 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0025_alter_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='how_contacted',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата'),
        ),
        migrations.CreateModel(
            name='ContactTypeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='название опции')),
                ('worker', models.ForeignKey(blank=True, limit_choices_to={'is_prosthetist': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'откуда обратились',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='how_contacted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.contacttypechoice', verbose_name='откуда обратились'),
        ),
    ]
