# Generated by Django 4.2 on 2023-07-10 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_remove_client_how_contacted_remove_job_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacttypechoice',
            options={'verbose_name': 'откуда обратились', 'verbose_name_plural': 'откуда обратились'},
        ),
    ]
