# Generated by Django 4.2 on 2023-07-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_remove_contacttypechoice_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('in work', 'принят в работу'), ('issued', 'выдан'), ('docs submitted', 'документы сданы'), ('payment to client', 'оплата клиенту'), ('payment', 'оплата')], default='in work', max_length=150, verbose_name='статус'),
        ),
    ]
