# Generated by Django 4.2 on 2023-07-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(choices=[('Moscow', 'Москва'), ('Moscow region', 'Московская область')], max_length=128, verbose_name='регион'),
        ),
    ]
