# Generated by Django 4.2 on 2023-07-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_alter_client_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
    ]
