# Generated by Django 4.2 on 2023-07-13 03:00

import clients.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_status_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='IPR',
        ),
        migrations.RemoveField(
            model_name='client',
            name='SNILS',
        ),
        migrations.RemoveField(
            model_name='client',
            name='SprMSE',
        ),
        migrations.AlterField(
            model_name='client',
            name='bank_details',
            field=models.FileField(blank=True, null=True, upload_to=clients.utils.client_directory_path, verbose_name='реквизиты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='parts',
            field=models.BooleanField(default=False, help_text='протезист дал комплектующие', verbose_name='комплектующие'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to=clients.utils.client_directory_path, verbose_name='паспорт'),
        ),
        migrations.AddField(
            model_name='client',
            name='ipr',
            field=models.FileField(blank=True, null=True, upload_to=clients.utils.client_directory_path, verbose_name='ИПР'),
        ),
        migrations.AddField(
            model_name='client',
            name='snils',
            field=models.FileField(blank=True, null=True, upload_to=clients.utils.client_directory_path, verbose_name='СНИЛС'),
        ),
        migrations.AddField(
            model_name='client',
            name='sprmse',
            field=models.FileField(blank=True, null=True, upload_to=clients.utils.client_directory_path, verbose_name='CпрМСЭ'),
        ),
    ]
