# Generated by Django 4.2 on 2023-07-13 03:08

import clients.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_remove_client_ipr_remove_client_snils_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bank_details',
            field=models.FileField(null=True, upload_to=clients.utils.client_directory_path, verbose_name='реквизиты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ipr',
            field=models.FileField(null=True, upload_to=clients.utils.client_directory_path, verbose_name='ИПР'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.FileField(null=True, upload_to=clients.utils.client_directory_path, verbose_name='паспорт'),
        ),
        migrations.AlterField(
            model_name='client',
            name='snils',
            field=models.FileField(null=True, upload_to=clients.utils.client_directory_path, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sprmse',
            field=models.FileField(null=True, upload_to=clients.utils.client_directory_path, verbose_name='CпрМСЭ'),
        ),
    ]
