# Generated by Django 4.2 on 2023-08-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_alter_client_bank_details_alter_client_ipr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contour',
        ),
        migrations.RemoveField(
            model_name='client',
            name='parts',
        ),
    ]
