# Generated by Django 4.2 on 2023-08-09 07:18

import clients.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_remove_client_contour_remove_client_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='passport',
        ),
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4, verbose_name='серия')),
                ('number', models.CharField(max_length=6, verbose_name='номер')),
                ('date_of_issue', models.DateField(verbose_name='дата выдачи')),
                ('who_issued', models.CharField(max_length=1024, verbose_name='кем выдан')),
                ('division_code', models.CharField(max_length=7, verbose_name='код подразделения')),
                ('scan', models.FileField(blank=True, null=True, upload_to=clients.models.Passport.passport_directory_path, verbose_name='скан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='клиент')),
            ],
        ),
    ]
