# Generated by Django 4.2 on 2023-08-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0039_alter_contact_options_alter_passport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(max_length=20, verbose_name='№ Счёта (р/с)')),
                ('bank', models.CharField(max_length=1024, verbose_name='в банке (название)')),
                ('BIC', models.CharField(max_length=8, verbose_name='БИК')),
                ('correspondent_account', models.IntegerField(max_length=20, verbose_name='к/с')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='клиент')),
            ],
        ),
    ]
