# Generated by Django 4.2 on 2023-08-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_bankdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=models.IntegerField(verbose_name='№ Счёта (р/с)'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='correspondent_account',
            field=models.IntegerField(verbose_name='к/с'),
        ),
    ]
