# Generated by Django 4.2 on 2023-08-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0041_alter_bankdetails_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=models.CharField(max_length=20, verbose_name='№ Счёта (р/с)'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='correspondent_account',
            field=models.CharField(max_length=20, verbose_name='к/с'),
        ),
    ]
