# Generated by Django 4.2 on 2023-08-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_alter_bankdetails_options_remove_client_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='snils',
            field=models.CharField(blank=True, null=True, verbose_name='СНИЛС'),
        ),
    ]
