# Generated by Django 4.2 on 2023-08-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_alter_client_snils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='clients.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='clients.client', verbose_name='клиент'),
        ),
    ]
