# Generated by Django 4.2 on 2023-08-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_alter_bankdetails_client_alter_contact_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='comment',
        ),
    ]
