# Generated by Django 4.2.4 on 2023-08-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_client_snils_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_finished',
            field=models.BooleanField(blank=True, null=True, verbose_name='завершена'),
        ),
    ]
