# Generated by Django 4.2.4 on 2023-08-24 07:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0049_alter_job_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=colorfield.fields.ColorField(choices=[('B6D7A8', 'In Work'), ('6AA84F', 'Issued'), ('34A853', 'Docs Submitted'), ('00FFFF', 'Payment To Client'), ('6D9EEB', 'Payment')], default='B6D7A8', image_field=None, max_length=18, samples=None),
        ),
    ]
