# Generated by Django 4.2.4 on 2023-08-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0051_alter_status_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='color',
        ),
    ]
