# Generated by Django 4.2.4 on 2023-08-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0053_status_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(choices=[('in work', 'B6D7A8'), ('issued', '6AA84F'), ('docs submitted', '34A853'), ('payment to client', '00FFFF'), ('payment', '6D9EEB')], default='in work', max_length=150, verbose_name='цвет'),
        ),
    ]
