version: '3'

volumes:
  pg_data:
  static:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./ortoreal/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/collected_static

  gateway:
    image: nginx:1.22.1
    ports:
      - 9000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    depends_on:
      - backend
