# Generated by Django 4.1.7 on 2023-04-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_prosthetist',
            field=models.BooleanField(default=False, verbose_name='Протезист'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=150, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=None, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname',
            field=models.CharField(blank=True, max_length=150, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=None, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=150, verbose_name='last name'),
        ),
    ]
