# Generated by Django 4.1.7 on 2023-04-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
