# Generated by Django 4.2 on 2023-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь является менеджером.', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_prosthetist',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь является протезистом.', verbose_name='Протезист'),
        ),
    ]
