# Generated by Django 4.2 on 2023-07-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'работник', 'verbose_name_plural': 'работники'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='отметьте, если пользователь является менеджером.', verbose_name='менеджер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_prosthetist',
            field=models.BooleanField(default=False, help_text='отметьте, если пользователь является протезистом.', verbose_name='протезист'),
        ),
    ]
