# Generated by Django 4.1.7 on 2023-04-03 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='parts',
            field=models.ManyToManyField(to='inventory.item', verbose_name='Комплектующие'),
        ),
    ]
