# Generated by Django 4.1.7 on 2023-04-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_date_added_alter_product_parts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Комплектующее на складе', 'verbose_name_plural': 'Комплектующие на складе'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Модель комплектующего', 'verbose_name_plural': 'Модели комплектующих'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Производитель/поставщик', 'verbose_name_plural': 'Производители/поставщики'},
        ),
        migrations.RemoveField(
            model_name='part',
            name='supplier',
        ),
        migrations.AddField(
            model_name='part',
            name='units',
            field=models.CharField(blank=True, choices=[('pairs', 'пар'), ('pieces', 'шт.'), ('sets', 'компл.'), ('packages', 'упак.')], max_length=32, verbose_name='Единицы'),
        ),
        migrations.AddField(
            model_name='part',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor', verbose_name='Производитель/поставщик'),
        ),
        migrations.AlterField(
            model_name='item',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.part', verbose_name='Комплектующее'),
        ),
    ]
