# Generated by Django 4.1.7 on 2023-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_part_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='units',
            field=models.CharField(blank=True, choices=[('пар', 'Pairs'), ('шт.', 'Piece'), ('компл.', 'Sets'), ('упак.', 'Packages')], max_length=32, verbose_name='Единицы'),
        ),
    ]
