# Generated by Django 4.1.7 on 2023-04-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_part_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='part',
            name='units',
            field=models.CharField(blank=True, choices=[('pairs', 'пар'), ('pieces', 'шт.'), ('sets', 'компл.'), ('packages', 'упак.')], max_length=32, verbose_name='Единицы'),
        ),
    ]
