# Generated by Django 4.1.7 on 2023-04-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('inventory', '0006_part_note_alter_part_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='operation',
            field=models.CharField(choices=[('RECEPTION', 'Приход'), ('TOOK', 'Взял'), ('RETURNED', 'Вернул')], max_length=32, verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part', verbose_name='Комплектующее'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient', verbose_name='Инвалид'),
        ),
        migrations.AlterField(
            model_name='part',
            name='note',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Цена, руб.'),
        ),
    ]
