# Generated by Django 4.1.7 on 2023-04-03 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_prosthetist_user_surname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_alter_inventorylog_operation_alter_inventorylog_part_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='worker',
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='prosthetist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Протезист'),
        ),
        migrations.AlterField(
            model_name='product',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient', verbose_name='Инвалид'),
        ),
    ]
