# Generated by Django 4.1.7 on 2023-04-03 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_inventorylog_worker_inventorylog_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorylog',
            options={'verbose_name': 'Операция на складе', 'verbose_name_plural': 'Операции на складе'},
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='operation',
            field=models.CharField(choices=[('RECEIVED', 'Приход'), ('TOOK', 'Взял'), ('RETURNED', 'Вернул')], max_length=32, verbose_name='Операция'),
        ),
    ]
