# Generated by Django 4.1.7 on 2023-04-04 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_alter_inventorylog_options_alter_inventorylog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлено'),
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.CharField(choices=[('с1', 'C1'), ('с2', 'C2')], default='C2', max_length=16, verbose_name='Склад'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
