# Generated by Django 4.1.7 on 2023-04-05 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorylog_added_by_item_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='item',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.part', verbose_name='Артикул'),
        ),
    ]
