# Generated by Django 4.1.7 on 2023-04-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_item_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='date',
        ),
    ]
