# Generated by Django 4.1.7 on 2023-04-06 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_inventorylog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
