# Generated by Django 4.1.7 on 2023-04-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_inventorylog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
