# Generated by Django 4.1.7 on 2023-04-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0018_alter_part_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент'),
        ),
    ]
