# Generated by Django 4.1.7 on 2023-04-14 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_how_contacted_client_prosthetist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0020_alter_inventorylog_operation_alter_item_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProsthesisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Цена')),
                ('region', models.CharField(choices=[('Moscow', 'Москва'), ('Moscow region', 'Московская область')], max_length=128, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Модель протеза',
                'verbose_name_plural': 'Модели протезов',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='item',
            name='prosthetist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Протезист'),
        ),
        migrations.AlterField(
            model_name='item',
            name='warehouse',
            field=models.CharField(choices=[('S1', 'Склад 1'), ('S2', 'Склад 2')], max_length=16, null=True, verbose_name='Склад'),
        ),
    ]
