# Generated by Django 4.1.7 on 2023-04-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_part_options_alter_item_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='operation',
            field=models.CharField(choices=[('', '---выбрать---'), ('RECEIVED', 'Приход'), ('RETURNED', 'Возврат'), ('TOOK', 'Расход')], max_length=32, verbose_name='Операция'),
        ),
    ]
