# Generated by Django 4.1.7 on 2023-04-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_alter_status_name'),
        ('inventory', '0027_alter_inventorylog_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='client',
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.job', verbose_name='Клиент'),
        ),
    ]
