# Generated by Django 4.1.7 on 2023-04-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_remove_inventorylog_client_inventorylog_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.order', verbose_name='Заказ'),
        ),
    ]
