# Generated by Django 4.1.7 on 2023-04-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_inventorylog_added_by_alter_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='Не на складе'),
            preserve_default=False,
        ),
    ]
