# Generated by Django 4.1.7 on 2023-04-27 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_alter_status_name'),
        ('inventory', '0030_item_is_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_taken',
        ),
        migrations.AddField(
            model_name='item',
            name='reserved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_items', to='clients.job', verbose_name='Резерв'),
        ),
    ]
