# Generated by Django 4.1.7 on 2023-04-27 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_remove_item_is_taken_item_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
