# Generated by Django 4.1.7 on 2023-05-01 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_alter_client_prosthetist_alter_job_prosthetist'),
        ('inventory', '0032_alter_inventorylog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='items',
            field=models.ManyToManyField(to='inventory.item', verbose_name='Комплектующие'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='operation',
            field=models.CharField(choices=[('', '---выбрать---'), ('RECEPTION', 'Приход'), ('RETURN', 'Возврат'), ('TAKE', 'Расход')], max_length=32, verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='item',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='clients.job', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='item',
            name='reserved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_items', to='clients.job', verbose_name='Резерв'),
        ),
    ]
