# Generated by Django 4.1.7 on 2023-05-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_inventorylog_items_alter_inventorylog_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='part',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='quantity',
        ),
    ]
