# Generated by Django 4.2 on 2023-05-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_remove_inventorylog_part_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_added',
            new_name='date',
        ),
    ]
