# Generated by Django 4.2 on 2023-05-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_rename_date_added_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='items',
            field=models.ManyToManyField(related_name='logs', to='inventory.item', verbose_name='Комплектующие'),
        ),
    ]
