# Generated by Django 4.2 on 2023-05-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='warehouse',
        ),
    ]
