# Generated by Django 4.2 on 2023-05-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_item_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='name',
        ),
    ]
