# Generated by Django 4.2 on 2023-05-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_remove_warehouse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='warehouse',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', 'Склад 1'), ('2', 'Склад 2')], null=True, verbose_name='Склад'),
        ),
    ]
