# Generated by Django 4.2 on 2023-05-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_item_warehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
