# Generated by Django 4.2 on 2023-05-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_alter_item_warehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProsthesisModel',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Комплектующая', 'verbose_name_plural': 'Комплектующие'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'модель комплектующей', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.AddField(
            model_name='prosthesis',
            name='region',
            field=models.CharField(choices=[('Moscow', 'Москва'), ('Moscow region', 'Московская область')], default='Moscow', max_length=128, verbose_name='Регион'),
            preserve_default=False,
        ),
    ]
