# Generated by Django 4.2 on 2023-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_delete_prosthesismodel_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='free_order',
            field=models.BooleanField(default=False, help_text='Запретить удаление из заказа при пересчёте резервов.', verbose_name='Свободный заказ'),
        ),
        migrations.AddField(
            model_name='part',
            name='minimum_remainder',
            field=models.SmallIntegerField(blank=True, help_text='Оставьте пустым или 0, чтобы выключить неснижаемый остаток.', null=True, verbose_name='Неснижаемый остаток'),
        ),
    ]
