# Generated by Django 4.2 on 2023-05-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_item_free_order_part_minimum_remainder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='units',
            field=models.CharField(blank=True, choices=[('pairs', 'пар'), ('pieces', 'шт.'), ('sets', 'компл.'), ('packages', 'упак.'), ('items', 'ед.'), ('meters', 'м.')], default='items', max_length=32, verbose_name='Единицы'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
