# Generated by Django 4.2 on 2023-05-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_alter_part_units_alter_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Цена, руб.'),
        ),
    ]
