# Generated by Django 4.2 on 2023-05-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_alter_manufacturer_options_remove_part_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Цена, руб.'),
        ),
    ]
