# Generated by Django 4.2 on 2023-05-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_part_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание'),
        ),
    ]
