# Generated by Django 4.2 on 2023-05-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_item_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Цена, руб.'),
            preserve_default=False,
        ),
    ]
