# Generated by Django 4.2 on 2023-05-31 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_alter_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'производитель', 'verbose_name_plural': 'производители'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'модель комплектующей', 'verbose_name_plural': 'номенклатура'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'поставщик', 'verbose_name_plural': 'поставщики'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='vendor',
        ),
        migrations.AddField(
            model_name='item',
            name='arrived',
            field=models.BooleanField(default=False, verbose_name='Пришло'),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor2',
            field=models.BooleanField(default=False, verbose_name='Поставщик 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='current',
            field=models.BooleanField(default=True, verbose_name='текущий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='part',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.manufacturer', verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='part',
            name='minimum_remainder',
            field=models.SmallIntegerField(blank=True, help_text='Оставьте пустым или 0, чтобы выключить неснижаемый остаток.', null=True, verbose_name='неснижаемый остаток'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='part',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='примечание'),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='цена, руб.'),
        ),
        migrations.AlterField(
            model_name='part',
            name='units',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='единицы'),
        ),
        migrations.AlterField(
            model_name='part',
            name='vendor',
            field=models.ForeignKey(limit_choices_to=models.Q(('name', '2'), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor', verbose_name='поставщик'),
        ),
        migrations.AlterField(
            model_name='part',
            name='vendor_code',
            field=models.CharField(max_length=256, unique=True, verbose_name='артикул'),
        ),
    ]
