# Generated by Django 4.2 on 2023-05-31 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_alter_job_prosthesis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0058_alter_manufacturer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorylog',
            options={'verbose_name': 'операция на складе', 'verbose_name_plural': 'операции на складе'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'комплектующая', 'verbose_name_plural': 'комплектующие'},
        ),
        migrations.AlterModelOptions(
            name='prosthesis',
            options={'verbose_name': 'протез', 'verbose_name_plural': 'протезы'},
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='items',
            field=models.ManyToManyField(related_name='logs', to='inventory.item', verbose_name='комплектующие'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.job', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='operation',
            field=models.CharField(choices=[('', '---выбрать---'), ('RECEPTION', 'Приход'), ('RETURN', 'Возврат'), ('TAKE', 'Расход')], max_length=32, verbose_name='операция'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='prosthetist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='протезист'),
        ),
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='цена, руб.'),
        ),
        migrations.AlterField(
            model_name='prosthesis',
            name='kind',
            field=models.CharField(blank=True, max_length=1024, verbose_name='вид'),
        ),
        migrations.AlterField(
            model_name='prosthesis',
            name='name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='prosthesis',
            name='number',
            field=models.CharField(max_length=150, unique=True, verbose_name='номер изделия'),
        ),
        migrations.AlterField(
            model_name='prosthesis',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='prosthesis',
            name='region',
            field=models.CharField(choices=[('Moscow', 'Москва'), ('Moscow region', 'Московская область')], max_length=128, verbose_name='регион'),
        ),
    ]
