# Generated by Django 4.2 on 2023-05-31 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='warehouse',
        ),
    ]
