# Generated by Django 4.2 on 2023-07-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_remove_item_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosthesis',
            name='name',
        ),
        migrations.AlterField(
            model_name='prosthesis',
            name='kind',
            field=models.CharField(blank=True, choices=[('1', 'тип 1'), ('2', 'тип 2'), ('3', 'тип 3'), ('4', 'тип 4')], max_length=1024, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='prosthesis',
            name='number',
            field=models.CharField(max_length=512, unique=True, verbose_name='артикул'),
        ),
    ]
