# Generated by Django 4.2 on 2023-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_remove_prosthesis_name_alter_prosthesis_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='minimum_remainder',
            field=models.SmallIntegerField(blank=True, help_text='Оставьте пустым или 0, чтобы выключить неснижаемый остаток', null=True, verbose_name='неснижаемый остаток'),
        ),
    ]
