# Generated by Django 4.2 on 2023-07-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_alter_part_minimum_remainder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='minimum_remainder',
            field=models.SmallIntegerField(default=0, verbose_name='неснижаемый остаток'),
        ),
    ]
