# Generated by Django 4.2 on 2023-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_alter_part_minimum_remainder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='номер счёта'),
        ),
    ]
