# Generated by Django 4.2.4 on 2023-08-21 02:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_order_vendor_alter_item_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='номер счёта')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order', verbose_name='заказ')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'заказ поставщику',
                'verbose_name_plural': 'заказы поставщикам',
            },
        ),
    ]
