# Generated by Django 4.2.4 on 2023-09-03 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0067_remove_order_invoice_number_remove_order_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProsthetistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosthetist', to='inventory.item', verbose_name='комплектующая')),
                ('prosthetist', models.ForeignKey(limit_choices_to={'is_prosthetist': True}, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='протезист')),
            ],
            options={
                'verbose_name': 'инвентарь у протезиста',
            },
        ),
    ]
