# Generated by Django 4.2.4 on 2023-09-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_prosthetistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prosthetistitem',
            options={'verbose_name': 'инвентарь у протезиста', 'verbose_name_plural': 'инвентарь у протезиста'},
        ),
    ]
