# Generated by Django 4.2.4 on 2023-09-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_alter_prosthetistitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='текущий'),
        ),
    ]
