# Generated by Django 4.2.4 on 2023-09-15 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_vendororder_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendororder',
            name='order',
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='дата'),
        ),
    ]
