# Generated by Django 4.2.4 on 2023-09-15 03:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0071_remove_vendororder_order_alter_vendororder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='current',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='номер счёта'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='текущий'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor', verbose_name='поставщик'),
        ),
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.ForeignKey(blank=True, default=inventory.models.Order.get_current, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='дата'),
        ),
        migrations.DeleteModel(
            name='VendorOrder',
        ),
    ]
