# Generated by Django 4.2.5 on 2023-09-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_remove_order_current_order_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='номер счёта'),
        ),
    ]
