# Generated by Django 4.2.5 on 2023-10-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_item_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='номер счёта'),
        ),
    ]
