# Generated by Django 4.2.5 on 2023-10-04 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_inventorylog_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.order', verbose_name='заказ'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='номер')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'счета',
            },
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.invoice', verbose_name='счёт'),
        ),
        migrations.AddField(
            model_name='item',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.invoice', verbose_name='счёт'),
        ),
    ]
