# Generated by Django 4.2.7 on 2023-12-01 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0057_alter_client_address'),
        ('inventory', '0076_alter_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosthesis',
            name='price_end_date',
            field=models.DateField(null=True, verbose_name='Конец действия цены'),
        ),
        migrations.AddField(
            model_name='prosthesis',
            name='price_start_date',
            field=models.DateField(null=True, verbose_name='Начало действия цены'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.job', verbose_name='работа'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='operation',
            field=models.CharField(choices=[('RECEPTION', 'Приход'), ('RETURN', 'Возврат'), ('TAKE', 'Расход')], max_length=32, verbose_name='операция'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=100, unique=True, verbose_name='номер'),
        ),
    ]
